var orderHistory = [
  {
    productInfo: 'JavaScript for impatient programmers by Raushmayer, Dr. Axel',
    retailPrice: '$31.55',
    totalPaid: '$34.00',
    orderPlaced: 'August 4, 2020',
    dateDelivered: 'August 8, 2020',
    shippedTo: 'JS Masher',
    orderNumber: '114-3941689-8772232',
    returnWindow: 'Sep 7, 2020',
    buyItAgain: 'true',
    viewYourItem: 'true',
    accessOrderDetails: 'true',
    accessInvoice: 'true',
    productReview: 'true',
    productSupport: 'false',
    directlyHandedToResident: 'false',
    image: 'true'
  },
  {
    productInfo: 'The Timeless Way of Building by Alexander, Christopher',
    retailPrice: '$41.33',
    totalPaid: '$44.53',
    orderPlaced: 'July 19, 2020',
    dateDelivered: 'July 20, 2020',
    shippedTo: 'JS Masher',
    orderNumber: '113-9984268-1280257',
    returnWindow: 'August 19, 2020',
    buyItAgain: 'true',
    viewYourItem: 'true',
    accessOrderDetails: 'true',
    accessInvoice: 'true',
    productReview: 'true',
    productSupport: 'false',
    directlyHandedToResident: 'true',
    image: 'true'

  },
  {
    productInfo: 'Gamecube Controller Adapter. Super Smash Bros witch Gamecube Adapter for WII UIEvent, PC. SUPport Turbo and Vibration Features. No Driver and No Lag-Gamecube Adapter',
    retailPrice: '$15.98',
    totalPaid: '$17.22',
    orderPlaced: 'July 4, 2020',
    dateDelivered: 'July 7, 2020',
    shippedTo: 'JS Masher',
    orderNumber: '114-2875557-9059409',
    returnWindow: 'August 5, 2020',
    buyItAgain: 'true',
    viewYourItems: 'true',
    accessOrderDetails: 'true',
    accessInvoice: 'true',
    productReview: 'true',
    productSupport: 'false',
    directlyHandedToResident: 'true',
    image: 'true'
  },
  {
    productInfo: ['GameCube Controller-Super Smash Bros. Edition (Nintendo Switch)', 'The Art of Sql by Faroult, Stephane'],
    retailPrice: ['$94.95', '$33.99'],
    totalPaid: ['$138.93'],
    orderPlaced: ['July 3, 2020'],
    dateDelivered: ['July 5, 2020'],
    shippedTo: ['JS Masher'],
    orderNumber: ['113-2883177-2648248'],
    returnWindow: ['August 4, 2020'],
    buyItAgain: ['true'],
    viewYourItems: ['true'],
    accessOrderDetails: ['true'],
    accessInvoice: ['true'],
    productReview: ['true'],
    productSupport: ['true'],
    directlyHandedToResident: ['true'],
    image: ['true']
  }
];
